### ISSUE TITLE
Issue with select applet command in dart_pcsc_example.dart on windows

### ISSUE THREAD

**Issue by t-eli** [jjanku/dart_pcsc#2]
Hello,

I am trying to run the example program in **dart_pcsc_example.dart** with the command ```[0x00, 0xa4, 0x04, 0x00]``` which i believe should select the default applet, but the response is always a random 2 bytes: 

```
Readers: [Alcor Micro USB Smart Card Reader 0, Microsoft UICC ISO Reader 4fff2ad5 0]
Waiting for card
Connecting to card in Alcor Micro USB Smart Card Reader 0
Transmitting
Status: 0x8000
PS D:\codelab\dart_pcsc_test> dart run .\main.dart
Readers: [Alcor Micro USB Smart Card Reader 0, Microsoft UICC ISO Reader 4fff2ad5 0]
Waiting for card
Connecting to card in Alcor Micro USB Smart Card Reader 0
Transmitting
Status: 0xd030
```

I run the program  on 2 machines on  windows 10 and windows 11 with different card readers but still the same random results.
I also tried multiple cards.

**Comment by jjanku** [comment]
Hi @T-eli , thanks for the report! I'm sorry for taking so long to reply. The issue should hopefully be fixed now and the patch is available in the latest release (v2.0.2). If the bug persists, please reopen this issue.

**Comment by t-eli** [comment]
Hello @jjanku , I can confirm the issue is resolved, thank you for the fix.

**Comment by sunshineco** [comment]
Chiming in to say that I too confirm that the issue is resolved. A week ago when I tried this library, random results were returned on every run. The present version, on the other hand, returns correct results on every run. Thank you for the fix.

**Comment by jjanku** [comment]
> Chiming in to say that I too confirm that the issue is resolved. A week ago when I tried this library, random results were returned on every run. The present version, on the other hand, returns correct results on every run. Thank you for the fix.

Glad to hear that, thanks for the confirmation!
